### ISSUE TITLE
Readme: Cases -> Inflections

### ISSUE THREAD

**Issue by Loknar** [alexharri/beygla#19]
Mér skilst að enska orðið inflections sé notað fyrir beygingar orða, það væri held ég réttara að segja t.d. "Icelandic names have four inflections", og ef til viłl réttast að segja "Icelandic names generally have four inflections" þar sem sum nöfn hafa jafnvel fleiri en eina almennt samþykkta beygingu :smile: , til dæmis nafnið Björn (til Bjarnar, en líka til Björns).

Sjá t.d. [Cambridge dictionary: inflection](https://dictionary.cambridge.org/dictionary/english/inflection).

**Comment by alexharri** [comment]
Mér skilst að declension sé _tegund_ af inflection. Inflection virðist vera almennara hugtak.

> In linguistics, declension is the changing of the form of a word [...] by way of some inflection.

Varðandi hugtakið "case" má t.d. sjá þessa línu úr https://en.wikipedia.org/wiki/Icelandic_grammar:

> Nouns, adjectives and pronouns are _declined in four cases_ and two numbers, singular and plural.

Ég er ekki lærður í þessu, svo endilega leiðréttu mig ef þetta er rangt!
